
services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: manageOrder

volumes:
  db_data: {}


