spring.application.name=appOrders

spring.datasource.url=jdbc:postgresql://localhost:5432/coreDB
spring.datasource.username=postgres
spring.datasource.password=root

spring.liquibase.change-log=classpath:db.changelog/29-01-changelog.yaml
spring.liquibase.enabled=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

security.token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
security.jwt.access_token_expiration=36000000
security.jwt.refresh_token_expiration=252000000


logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.enabled= true
spring.servlet.multipart.max-file-size= 10MB
spring.servlet.multipart.max-request-size= 10MB