spring.application.name=appOrders

spring.datasource.url=jdbc:postgresql://localhost:5432/coreDB
spring.datasource.username=postgres
spring.datasource.password=root

spring.liquibase.change-log=classpath:db.changelog/29-01-changelog.yaml
spring.liquibase.enabled=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


